version: '2'

networks:
  pharma:

services:
  ca_manufacturer:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.manufacturer.pharma.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - ORDERER_OPERATIONS_LISTENADDRESS=127.0.01:7054
      - ORDERER_METRICS_PROVIDER=prometheus
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/manufacturer:/etc/hyperledger/fabric-ca-server
    container_name: ca.manufacturer.pharma.com
    hostname: ca.manufacturer.pharma.com
    networks:
      - pharma

  ca_transporter:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.transporter.pharma.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
      - ORDERER_OPERATIONS_LISTENADDRESS=127.0.01:8054
      - ORDERER_METRICS_PROVIDER=prometheus
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/transporter:/etc/hyperledger/fabric-ca-server
    container_name: ca.transporter.pharma.com
    hostname: ca.transporter.pharma.com
    networks:
      - pharma
   
  ca_distributor:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.distributor.pharma.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=6054
      - ORDERER_OPERATIONS_LISTENADDRESS=127.0.01:6054
      - ORDERER_METRICS_PROVIDER=prometheus
    ports:
      - "6054:6054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/org1:/etc/hyperledger/fabric-ca-server
    container_name: ca.distributor.pharma.com
    hostname: ca.distributor.pharma.com
    networks:
      - pharma

  ca_retailer:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.retailer.pharma.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=5054
      - ORDERER_OPERATIONS_LISTENADDRESS=127.0.01:5054
      - ORDERER_METRICS_PROVIDER=prometheus
    ports:
      - "5054:5054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/org2:/etc/hyperledger/fabric-ca-server
    container_name: ca.retailer.pharma.com
    hostname: ca.retailer.pharma.com
    networks:
      - pharma

  ca_orderer:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9054
      - ORDERER_OPERATIONS_LISTENADDRESS=127.0.01:9054
      - ORDERER_METRICS_PROVIDER=prometheus 
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
    container_name: ca_orderer
    networks:
      - pharma

